name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.x
      - name: Restore dependencies
        run: dotnet restore src/Codewrinkles.HIBPDotNetCore.Client
      - name: Build
        run: dotnet build src/Codewrinkles.HIBPDotNetCore.Client --no-restore
      - name: Test
        run: dotnet test tests/Codewrinkles.HIBPDotNetCore.Client.UnitTests --no-restore --no-build